create architecture
QuickHamster/java-explore-with-me pull request #1
Opened 2022-11-14 22:30 UTC by QuickHamster

2022-11-29 17:09 UTC, kukolev requested changes

2022-11-29 17:09 UTC, kukolev commented on ewm-main-service/src/main/java/ru/practicum/ewm/category/controller/CategoryControllerAdmin.java
> +    @PostMapping()
Скобки () здесь лишние и только отвлекают. Нужно убрать скобки.

2022-11-29 17:09 UTC, kukolev commented on ewm-main-service/src/main/java/ru/practicum/ewm/category/controller/CategoryControllerPublic.java
> +        log.info("Get all category: from {}, size {}.", from, size);
По моему лучше написать во множественном числе: Get all categories.

2022-11-29 17:09 UTC, kukolev commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/controller/EventControllerPublic.java
> +        statsClient.postStats(StatMapper.toEndpointHitDto("ewm-main-server", request));
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-11-29 17:09 UTC, kukolev commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +        if (!event.getState().equals(EventState.PENDING)) {
Валидации лучше вынести в отдельный приватный метод. Тогда каждый метод будет отвечать за свою часть функционала и код будет проще анализировать. Код при этом может выглядеть примерно так:

```
public SomeResult someMethod(...) {
    validateSomething(...);
    // business-logic here
}

private void validateSomething(...) {
    if (/* ! check something /*) {
        throw new SomeException();
    }
}

```

Таким образом в методе someMethod визуально будет проще найти бизнес-логику, ради которой этот метод и создавался.

2022-11-29 17:09 UTC, kukolev commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +        if (states == null) {
Вместо этой конструкции лучше было бы использовать тернарный оператор:
`itemRequest = <условие> ? <значение если true> : <значение если false> ;`
Так код будет проще.

Подробнее о тернарном операторе можно почитать тут: https://www.baeldung.com/java-ternary-operator

Аналогично лучше поправить и в остальных подобных случаях.

2022-11-29 17:09 UTC, kukolev commented on ewm-main-service/src/main/java/ru/practicum/ewm/request/service/RequestServiceImpl.java
> +        if (event.getInitiator().getId().equals(userId)) {
Валидации лучше вынести в отдельный приватный метод. Тогда каждый метод будет отвечать за свою часть функционала и код будет проще анализировать. Код при этом может выглядеть примерно так:

```
public SomeResult someMethod(...) {
    validateSomething(...);
    // business-logic here
}

private void validateSomething(...) {
    if (/* ! check something /*) {
        throw new SomeException();
    }
}

```

Таким образом в методе someMethod визуально будет проще найти бизнес-логику, ради которой этот метод и создавался.

2022-11-29 17:09 UTC, kukolev commented on ewm-main-service/src/main/java/ru/practicum/ewm/user/model/User.java
> +    public int hashCode() {
Текущая реализация фактически означает константный хэшкод. Это плохая практика, т.к. использование такого объекта в качестве ключа в HashMap/HashSet приведет уменьшению скорости доступа по ключу до O(n). Здесь это роли не играет, но вообще это плохая практика. Лучше воспользоваться авто-генерацией методов equals и hashCode в IDEA или написать метод самостоятельно, используя поля класса.

2022-11-29 17:09 UTC, kukolev commented on ewm-main-service/src/main/resources/schema.sql
> +/*DROP TABLE IF EXISTS compilations cascade;
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-11-29 17:09 UTC, kukolev commented on ewm-main-service/src/main/resources/schema.sql
> +    --location_id        bigint REFERENCES locations (location_id) NOT NULL,
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-11-29 17:09 UTC, kukolev commented on ewm-stats-service/src/main/java/ru/practicum/stats/service/StatServiceImpl.java
> +        if (!uris.isEmpty()) {
Вместо этой конструкции лучше было бы использовать тернарный оператор:
`itemRequest = <условие> ? <значение если true> : <значение если false> ;`
Так код будет проще.

Подробнее о тернарном операторе можно почитать тут: https://www.baeldung.com/java-ternary-operator

Аналогично лучше поправить и в остальных подобных случаях.

2022-11-29 18:04 UTC, QuickHamster commented on ewm-main-service/src/main/java/ru/practicum/ewm/category/controller/CategoryControllerAdmin.java
> +    @PostMapping()
++

2022-11-29 18:05 UTC, QuickHamster commented on ewm-main-service/src/main/java/ru/practicum/ewm/category/controller/CategoryControllerPublic.java
> +        log.info("Get all category: from {}, size {}.", from, size);
++

2022-11-29 18:08 UTC, QuickHamster commented on ewm-main-service/src/main/resources/schema.sql
> +    --location_id        bigint REFERENCES locations (location_id) NOT NULL,
++

2022-11-29 18:08 UTC, QuickHamster commented on ewm-main-service/src/main/resources/schema.sql
> +/*DROP TABLE IF EXISTS compilations cascade;
++

2022-11-29 19:30 UTC, QuickHamster commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +        if (!event.getState().equals(EventState.PENDING)) {
++

2022-11-29 19:43 UTC, QuickHamster commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +        if (states == null) {
++

2022-11-29 20:45 UTC, QuickHamster commented on ewm-main-service/src/main/java/ru/practicum/ewm/user/model/User.java
> +    public int hashCode() {
++

2022-11-29 20:49 UTC, QuickHamster commented on ewm-stats-service/src/main/java/ru/practicum/stats/service/StatServiceImpl.java
> +        if (!uris.isEmpty()) {
++

2022-11-29 20:50 UTC, QuickHamster commented on ewm-main-service/src/main/java/ru/practicum/ewm/request/service/RequestServiceImpl.java
> +        if (event.getInitiator().getId().equals(userId)) {
++

2022-11-29 21:00 UTC, QuickHamster commented on ewm-main-service/src/main/java/ru/practicum/ewm/event/controller/EventControllerPublic.java
> +        statsClient.postStats(StatMapper.toEndpointHitDto("ewm-main-server", request));
++

2022-12-01 09:23 UTC, kukolev requested changes

2022-12-01 09:23 UTC, kukolev commented on ewm-main-service/src/main/java/ru/practicum/ewm/validation/CategoryValidator.java
> +    public void validationCategoryByNameOrThrow(String categoryName) {
Нарушение кодстайла: Название метода лучше начинать с глагола, обозначающего действие над аргументами или над классом, которому принадлежит метод. Так назначение метода будет понятно сразу из названия. Нужно поправить.

2022-12-01 11:57 UTC, QuickHamster commented on ewm-main-service/src/main/java/ru/practicum/ewm/validation/CategoryValidator.java
> +    public void validationCategoryByNameOrThrow(String categoryName) {
++

2022-12-02 10:42 UTC, kukolev approved these changes

2022-12-02 19:11 UTC, merged